<?xml version="1.0"?>
<robot name="turtlebot_hardware" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="turtlebot_spacer" params="parent number x_loc y_loc z_loc">
    <joint name="spacer_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="spacer_${number}_link" />
    </joint>

    <link name="spacer_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gatlin/meshes/stacks/circles/68-02403-125_Spacer.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.003175" radius=".0127"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="turtlebot_standoff_1in" params="parent number x_loc y_loc z_loc">
    <joint name="standoff_1in_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_1in_${number}_link" />
    </joint>

    <link name="standoff_1in_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gatlin/meshes/stacks/circles/68-04552-1000-RA_Turtlebot_M-F_Standoff.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.0381" radius="0.011113"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="turtlebot_standoff_2in" params="parent number x_loc y_loc z_loc">
    <joint name="standoff_2in_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_2in_${number}_link" />
    </joint>

    <link name="standoff_2in_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gatlin/meshes/stacks/circles/68-04552-2000-RA_Turtlebot_M-F_Standoff.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.0635" radius="0.0381"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>


  <xacro:macro name="turtlebot_standoff_8in" params="parent number x_loc y_loc z_loc">
    <joint name="standoff_8in_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_8in_${number}_link" />
    </joint>

    <link name="standoff_8in_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gatlin/meshes/stacks/circles/68-02421-8000-RA_Turtlebot_F-F_Standoff.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.2032" radius="0.011113"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="turtlebot_standoff_kinect" params="parent number x_loc y_loc z_loc">
    <joint name="standoff_kinect_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_kinect_${number}_link" />
    </joint>

    <link name="standoff_kinect_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gatlin/meshes/stacks/circles/68-04556-RA_Kinect_Standoff_Assy.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.008585" radius="0.001111"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="turtlebot_support" params="parent number length x_loc y_loc z_loc">
    <joint name="support_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc+length/2}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="support_${number}_link" />
    </joint>

    <link name="support_${number}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <cylinder length="${length}" radius="0.005"/>
          <!-- <mesh filename="package://gatlin/meshes/stacks/circles/68-02421-8000-RA_Turtlebot_F-F_Standoff.dae"/> -->
        </geometry>
        <material name="gray">
          <color rgba=".75 .75 .75 1"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${length}" radius="0.005"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="stack_squares" params="parent offset top_plate">
    <!-- <turtlebot_spacer parent="${parent}" number="0" x_loc="-0.00254" y_loc="0.1114679" z_loc="0.062992"/>
    <turtlebot_spacer parent="${parent}" number="1" x_loc="-0.00254" y_loc="-0.1114679" z_loc="0.062992"/>
    <turtlebot_spacer parent="${parent}" number="2" x_loc="-0.07239" y_loc="-0.1114679" z_loc="0.062992"/>
    <turtlebot_spacer parent="${parent}" number="3" x_loc="-0.07239" y_loc="0.1114679" z_loc="0.062992"/> -->

    <joint name="plate_0_joint" type="fixed">
      <origin xyz="-0.04334 0  0.06775704" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="plate_0_link" />
    </joint>


    <link name="plate_0_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0"
          iyy="0.01" iyz="0.0"
          izz="0.01" />
      </inertial>
  
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gatlin/meshes/stacks/circles/plate_0_logo.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="0.233502 0.314845 0.006401"/>
        </geometry>
      </collision>
    </link>

    <turtlebot_support parent="${parent}" number="0" x_loc="0.0276402" y_loc="0.1314196" z_loc="0.0609803" length="0.6096"/>
    <turtlebot_support parent="${parent}" number="1" x_loc="0.0276402" y_loc="-0.1314196" z_loc="0.0609803" length="0.6096"/>
    <turtlebot_support parent="${parent}" number="2" x_loc="-0.092832" y_loc="-0.1314196" z_loc="0.0609803" length="0.6096"/>
    <turtlebot_support parent="${parent}" number="3" x_loc="-0.092832" y_loc="0.1314196" z_loc="0.0609803" length="0.6096"/>

    <joint name="plate_1_joint" type="fixed">
      <origin xyz="${0.04068+offset} 0 0.125" rpy="0 0 0" />
      <parent link="plate_0_link"/>
      <child link="plate_1_link" />
    </joint>

    <link name="plate_1_link">
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0"
          iyy="0.01" iyz="0.0"
          izz="0.01" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <!-- <mesh filename="package://gatlin/meshes/stacks/circles/plate_1_logo.dae"/> -->
          <box size="0.28 0.31 0.00635"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="0.28 0.31 0.00635"/>
        </geometry>
      </collision>
    </link>

    <!-- <turtlebot_standoff_2in parent="standoff_2in_0_link" number="4" x_loc="0" y_loc="0" z_loc="0.05715"/>
    <turtlebot_standoff_2in parent="standoff_2in_1_link" number="5" x_loc="0" y_loc="0" z_loc="0.05715"/>
    <turtlebot_standoff_2in parent="standoff_2in_2_link" number="6" x_loc="0" y_loc="0" z_loc="0.05715"/>
    <turtlebot_standoff_2in parent="standoff_2in_3_link" number="7" x_loc="0" y_loc="0" z_loc="0.05715"/> -->

    <joint name="plate_2_joint" type="fixed">
      <origin xyz="0 0 0.0575" rpy="0 0 0" />
      <parent link="plate_1_link"/>
      <child link="plate_2_link" />
    </joint>

    <link name="plate_2_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
          iyy="0.001" iyz="0.0"
          izz="0.001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <!-- <mesh filename="package://gatlin/meshes/stacks/circles/plate_1_logo.dae"/> -->
          <box size="0.28 0.31 0.00635"/>
        </geometry>
        <material name="white" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="0.28 0.31 0.00635"/>
        </geometry>
      </collision>
    </link>

    <!-- <turtlebot_standoff_kinect parent="plate_2_link" number="0" x_loc="-0.1024382" y_loc="0.098" z_loc="0.0032004"/>
    <turtlebot_standoff_kinect parent="plate_2_link" number="1" x_loc="-0.1024382" y_loc="-0.098" z_loc="0.0032004"/> -->

    <!-- <turtlebot_standoff_8in parent="standoff_2in_4_link" number="0" x_loc="0" y_loc="0" z_loc="0.05715"/>
    <turtlebot_standoff_8in parent="standoff_2in_5_link" number="1" x_loc="0" y_loc="0" z_loc="0.05715"/>
    <turtlebot_standoff_8in parent="standoff_2in_6_link" number="2" x_loc="0" y_loc="0" z_loc="0.05715"/>
    <turtlebot_standoff_8in parent="standoff_2in_7_link" number="3" x_loc="0" y_loc="0" z_loc="0.05715"/> -->

    <joint name="plate_3_joint" type="fixed">
      <origin xyz="0 0 ${top_plate}" rpy="0 0 0" />
      <parent link="plate_2_link"/>
      <child link="plate_3_link" />
    </joint>

    <link name="plate_3_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>
  
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <!-- <mesh filename="package://gatlin/meshes/stacks/circles/plate_2_logo.dae"/> -->
          <box size="0.28 0.31 0.00635"/>
        </geometry>
        <material name="white" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="0.28 0.31 0.00635"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>
</robot>
